name: hallo_doctor_client
version: 1.0.17+11
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.2.6
  all_sensors2: ^1.0.1
  audioplayers: ^5.2.1
  awesome_notifications: ^0.8.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.2
  cupertino_icons: ^1.0.2
  date_picker_timeline:
    git:
      url: https://github.com/ElmarakbyDev/DatePickerTimelineFlutter.git
  dotted_border: ^2.1.0
  email_validator: ^2.1.17
  file_picker: ^6.1.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^5.0.0
  firebase_database: ^10.2.2
  firebase_dynamic_links: ^5.4.8
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^2.0.0
  flutter_chat_types: 3.6.2
  flutter_chat_ui: 1.6.10
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_firebase_chat_core: 1.6.7
  flutter_form_builder: ^9.0.0
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.6
  fluttertoast: ^8.0.9
  form_builder_validators: ^9.0.0
  get: null
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.0
  google_sign_in_ios: ^5.7.0
  http: ^0.13.4
  iconsax: ^0.0.8
  image_pickers: ^2.0.4+7
  intl: ^0.18.1
  jiffy: ^6.2.1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^2.4.0
  mime: ^1.0.2
  myfatoorah_flutter: ^3.0.6
  open_file: ^3.2.1
  package_info_plus: ^5.0.1
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^11.1.0
  provider: ^6.0.0
  rich_text_view: ^1.3.0
  string_validator: ^1.0.0
  timeago: ^3.6.0
  timezone: ^0.9.0
  url_launcher: ^6.2.2
  uuid: ^3.0.6
  video_player: ^2.8.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
dependency_overrides:
  intl: ^0.18.1
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: MyStudent
      fonts:
        - asset: assets/fonts/icon/MyStudent.ttf

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/ic_launcher.png"
